@startuml
left to right direction
skinparam packageStyle rectangle
:user:
:author:
rectangle soilandgreen {
  user -- (season calender)
  user -- (select corps)
  (select corps) -- author
  user -- (plan gardening project)
  author -- (register)
  author -- (edit corp)
  author -- (determine level)
  }

@enduml