@startuml
DataAccess - [dba-sog]
Rest - [backend-sog]
[backend-sog] ..> [dba-sog] : uses
HTTP - [frontend-sog]
[frontend-sog] ..> Rest : access

note right of [frontend-sog]

  * Android gradle
  * Web node-js Vue.js npm

end note

note right of [backend-sog]
  * spring-boot for rest-service; jpa liquibase maven
end note

note right of [dba-sog]
  * spring-boot-module hibernate; postgres-driver
end note

@enduml